import type { CSSProperties } from "react";
import { baseFont, displayFont, editorTheme } from "../editorStyles";

export const layoutStyles = {
  shell: {
    display: "flex",
    width: "100%",
    height: "100dvh",
    overflow: "hidden",
    background: editorTheme.background,
    color: editorTheme.text,
    fontFamily: baseFont,
  },
  sidebar: {
    width: 230,
    flexShrink: 0,
    borderRight: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
    display: "flex",
    flexDirection: "column",
  },
  header: {
    padding: 18,
    borderBottom: `1px solid ${editorTheme.border}`,
    background: editorTheme.surface,
  },
  titleInput: {
    marginTop: 8,
    width: "100%",
    border: "none",
    background: "transparent",
    color: editorTheme.text,
    fontSize: 18,
    fontWeight: 700,
    fontFamily: displayFont,
    outline: "none",
    padding: 0,
  },
  thumbs: { flex: 1, overflowY: "auto", padding: 14, display: "grid", gap: 12 },
  thumbRow: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: "22px 1fr",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: 6,
    border: `1px solid ${editorTheme.border}`,
    borderRadius: 8,
    background: editorTheme.surface,
    color: editorTheme.text,
    cursor: "pointer",
    boxShadow: "0 1px 2px rgba(16,19,35,0.04)",
  },
  thumbDragHandle: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 18,
    height: 18,
    borderRadius: 4,
    border: `1px solid ${editorTheme.borderStrong}`,
    background: editorTheme.surfaceSubtle,
    color: editorTheme.mutedStrong,
    display: "grid",
    placeItems: "center",
    fontSize: 13,
    lineHeight: 1,
    cursor: "grab",
    touchAction: "none",
    userSelect: "none",
  },
  thumbNumber: {
    color: editorTheme.mutedStrong,
    fontSize: 11,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  topbar: {
    minHeight: 68,
    flexShrink: 0,
    padding: "9px 18px",
    borderBottom: `1px solid ${editorTheme.border}`,
    background: "rgba(255,255,255,0.94)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  topbarTitle: {
    minWidth: 160,
    maxWidth: 280,
    overflow: "hidden",
    flexShrink: 1,
  },
  currentTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: editorTheme.text,
    fontFamily: displayFont,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  meta: {
    marginTop: 4,
    fontSize: 12,
    color: editorTheme.mutedStrong,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  toolbar: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap",
    justifyContent: "flex-end",
    minWidth: 0,
    flex: "1 1 auto",
  },
  toolbarGroup: {
    minHeight: 40,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: 2,
    borderRadius: 9,
    border: `1px solid ${editorTheme.border}`,
    background: editorTheme.surfaceSubtle,
    flexShrink: 0,
  },
} satisfies Record<string, CSSProperties>;
